site_name: pyadi-dt
site_description: Tools for managing device trees
site_author: Analog Devices, Inc.

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
    - Home: index.md
    - Access Models: access.md
    - Parts Layers: parts.md
    - Utilities: utils.md
    - CLI Reference: cli.md
    - Module Reference: ref.md

repo_url: https://github.com/analogdevicesinc/pyadi-dt

markdown_extensions:
    # - attr_list
    - mkdocs-click

plugins:
  - search
  - mkdocstrings
